# Generated by Django 4.0.4 on 2022-05-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('idInstrumento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=15)),
                ('marca', models.CharField(max_length=15)),
                ('color', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
                ('codigo', models.CharField(max_length=15)),
                ('stock', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='instrumentos/')),
            ],
        ),
    ]
