# Generated by Django 4.0.4 on 2022-05-17 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_instrumento_categoria_alter_categoria_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='tipo',
        ),
    ]
