# Generated by Django 4.0.4 on 2022-05-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_instrumento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
